# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

sudo: required

warnings_are_errors=FALSE

notifications:
  email:
    on_success: change
    on_failure: change
