---
title: "mplyr"
author: "Giuseppe Paleologo"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

mplyr helps users manipulate `array` objects, by offering alignment, split-apply-reduce, join and accumulation operations. The syntax is not unlike `dplyr`, hence the name.

```{r}

data(loadings)
axes(loadings) <- c('date','id')
summary(loadings)
nr <- 14
  nc <- 8
  set.seed(3141592)
  A <- matrix(rnorm(nr*nc), nrow=nr, ncol=nc)
  A <- addNames(A)
  #  class(A) <- c('array','matrix')
  expect_identical(filter_array(A, ROWS=ROWS %in% c('R1', 'R2')), 
                   A[row.names(A) %in% c('R1', 'R2'),])
  expect_identical(filter_array(A, ROWS=c('R1', 'R2')), 
                   A[row.names(A) %in% c('R1', 'R2'),])
  expect_identical(filter_array(A, COLUMNS=COLUMNS %in% c('C1', 'C8')), 
                   A[,colnames(A) %in% c('C1', 'C8')])
  expect_identical(filter_array(A, COLUMNS=c('C1', 'C8')), 
                   A[,colnames(A) %in% c('C1', 'C8')])
  expect_identical(filter_array(A, COLUMNS=COLUMNS =='C1'), 
                   A[,colnames(A) == 'C1', drop=FALSE])
  expect_identical(filter_array(A, COLUMNS='C1'), 
                   A[,colnames(A) == 'C1', drop=FALSE])



The figure sizes have been customised so that you can easily put two images side-by-side. 

```{r, fig.show='hold'}
plot(1:10)
plot(10:1)
```

You can enable figure captions by `fig_caption: yes` in YAML:

    output:
      rmarkdown::html_vignette:
        fig_caption: yes

Then you can use the chunk option `fig.cap = "Your figure caption."` in **knitr**.

## More Examples

You can write math expressions, e.g. $Y = X\beta + \epsilon$, footnotes^[A footnote here.], and tables, e.g. using `knitr::kable()`.

```{r, echo=FALSE, results='asis'}
knitr::kable(head(mtcars, 10))
```

Also a quote using `>`:

> "He who gives up [code] safety for [code] speed deserves neither."
([via](https://twitter.com/hadleywickham/status/504368538874703872))
